"""empty message

Revision ID: 8dbee4e92072
Revises: 
Create Date: 2020-01-27 16:34:25.448003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dbee4e92072'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('home_team', sa.String(length=250), nullable=True),
    sa.Column('away_team', sa.String(length=250), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('blackout', 'auth_failure', 'waiting', 'downloading', 'decoding', 'skip_silence', 'obfuscating', 'moving', 'completed', name='gamestatus'), nullable=False),
    sa.Column('current_operation_progress', sa.Integer(), nullable=True),
    sa.Column('game_info', sa.String(length=250), nullable=True),
    sa.Column('download_attempts', sa.Integer(), nullable=True),
    sa.Column('download_start', sa.DateTime(), nullable=True),
    sa.Column('download_end', sa.DateTime(), nullable=True),
    sa.Column('next_attempt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('games')
    # ### end Alembic commands ###
